### ISSUE TITLE
Long picker item breaks picker view in iOS?

### ISSUE THREAD

**Issue by vikrantnegi** [danielweinmann/react-native-picker-dropdown#9]
When the picker item is too long for the picker to render in one line, it wraps into two lines which breaks the view of the picker select in the iOS. In Android, the picker adds ellipses for the long names. 

It should have the same behavior for the iOS as well.

![picker](https://user-images.githubusercontent.com/3294287/38012962-0338c110-3281-11e8-8c68-5f17d9bd2526.png)

**Comment by danielweinmann** [comment]
@vikrantnegi, I'm not maintaining this repo anymore. Please let me know if you're interested in doing so :)

**Comment by vikrantnegi** [comment]
@danielweinmann Thank you for the request, however, I've just started learning the react native and I'm not sure if I have enough knowledge and skills to maintain a repo.

**Comment by danielweinmann** [comment]
@vikrantnegi, no problems :) any contribution is very much welcome! Thanks for this one!
